package com.therealjoe24.astraios.gui;

public enum CanvasElementEvent {
    ELEMENT_MOUSE_DOWN, ELEMENT_MOUSE_UP, ELEMENT_MOUSE_MOVE, 
    ELEMENT_MOUSE_CLICK, ELEMENT_MOUSE_ENTER, ELEMENT_MOUSE_LEAVE, 
    ELEMENT_SELECT, ELEMENT_DESELECT,
}
